server:
  port: 8081
user:
  role:Developer
  alias:sotobotero
spring:
  jpa:
    show-sql:true
  datasource:
    url:jdbc:h2:mem:product
    username:sa
    password:qwerty
    driver-class-name:org.h2.Driver
