server:
  port: 8081
  
spring:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cliente
          uri: lb://cliente
          predicates:
          - Path=/cliente/**
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-url: http://localhost:8761/eureka
  instance:
    hostname: localhost
