server:
  port: 8081
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: clientes
          uri: lb://cliente
          predicates:
          - Path=/cliente/**  
        - id: productos
          uri: lb://producto
          predicates:
          - Path=/producto/**
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-url: http://localhost:8761/eureka
  instance:
    hostname: localhost
